name: Build & Push Docker Compose Services

on:
  push:
    branches:
      - main

jobs:
  docker-compose-build-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Build services
        run: docker compose -f docker-compose.yml build